name: github pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: xmflsct/action-publish-gatsby@v1
        with:
          publishBranch: 'master'
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
          name: 'Łukasz Sowa'
          email: 'lukasz@main.dev'